// Copyright 2026 Shinsuke Mori
// SPDX-License-Identifier: Apache-2.0

import { modelCosts } from "./costs.gen.ts";
import { vendorBlockOf } from "./invariants.ts";
import type { Model, ModelCost, Provider } from "./schema.ts";
import type { Vendor } from "./vendor-ids.ts";
import { isVendor } from "./vendors.ts";

/**
 * The vendor whose price sheet applies to a model, when one can be named: a
 * direct provider's vendor (defaulting to the provider id), or the backend's
 * vendor for a gateway model. A resolver provider's vendor is not bundled, so
 * it has none. `openai-compatible` is a vendor but names a protocol rather
 * than an upstream, so the embedded table simply has no sheet under it.
 */
export function costVendorOf(provider: Provider, model: Model): Vendor | undefined {
	if (provider.gateway) {
		return model.backend === undefined
			? undefined
			: provider.gateway.backends[model.backend]?.vendor;
	}
	const vendor = vendorBlockOf(provider)?.id ?? provider.id;
	return isVendor(vendor) ? vendor : undefined;
}

/**
 * The embedded models.dev price sheet for a model whose config omits `cost`:
 * the model's id looked up under its vendor (see {@link costVendorOf}) in the
 * snapshot generated by scripts/generate-costs.ts. Undefined when the vendor
 * is unknown or models.dev lists no price for the id — models.dev spells ids
 * the way each vendor does, so a config using vendor ids matches as-is.
 */
export function defaultCostOf(provider: Provider, model: Model): ModelCost | undefined {
	const vendor = costVendorOf(provider, model);
	return vendor === undefined ? undefined : modelCosts[vendor]?.[model.id];
}
