import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import * as z from "zod";

import { type ModelCost, ModelCostSchema, VendorSchema } from "../src/schema.ts";

// Emits src/costs.gen.ts: a snapshot of models.dev price sheets for the bundled
// vendors, so a model whose config omits `cost` still surfaces a price sheet
// through `meta`/`metaForRole` (see src/costs.ts). models.dev provider ids
// match the {@link VendorSchema} enum 1:1; `openai-compatible` is skipped because it
// names a protocol, not an upstream with a price list. Regenerate to refresh
// the prices (git history of the generated file tells you how stale it is):
//
//   pnpm generate-costs && pnpm format
//
// Every snapshotted price passes `ModelCostSchema`, so a models.dev unit
// mix-up (or a price above the sanity cap) fails the generation instead of
// shipping.

const API_URL = "https://models.dev/api.json";

/** Vendors with a models.dev price list (all but `openai-compatible`). */
const vendors = VendorSchema.options.filter((v) => v !== "openai-compatible");

// The slice of the models.dev dump this generator reads.
const ModelsDevCostSchema = z.looseObject({
	input: z.number().optional(),
	output: z.number().optional(),
	cache_read: z.number().optional(),
	cache_write: z.number().optional(),
});
const ModelsDevModalitiesSchema = z.looseObject({ output: z.array(z.string()).optional() });
const ModelsDevModelSchema = z.looseObject({
	cost: ModelsDevCostSchema.optional(),
	modalities: ModelsDevModalitiesSchema.optional(),
});
const ModelsDevProviderSchema = z.looseObject({
	models: z.record(z.string(), ModelsDevModelSchema),
});
const ModelsDevApiSchema = z.record(z.string(), ModelsDevProviderSchema);
type ModelsDevProvider = z.infer<typeof ModelsDevProviderSchema>;

const buckets = ["input", "output", "cacheRead", "cacheWrite"] as const;

/** Renders one model's sheet as a single TS object literal line. */
function renderCost(cost: ModelCost): string {
	const fields = buckets
		.filter((bucket) => cost[bucket] !== undefined)
		.map((bucket) => `${bucket}: ${String(cost[bucket])}`);
	return `{ ${fields.join(", ")} }`;
}

/**
 * Renders one vendor's sheets, one line per model, sorted by model id. Models
 * that don't output text (image generation, TTS, video) are skipped — the
 * catalog hands out language models, so their sheets would be dead weight.
 */
function renderVendor(provider: ModelsDevProvider): string[] {
	const entries: string[] = [];
	for (const id of Object.keys(provider.models).toSorted()) {
		const model = provider.models[id];
		const cost = model?.cost;
		if (cost && model.modalities?.output?.includes("text") === true) {
			const sheet = ModelCostSchema.parse({
				input: cost.input,
				output: cost.output,
				cacheRead: cost.cache_read,
				cacheWrite: cost.cache_write,
			});
			if (buckets.some((bucket) => sheet[bucket] !== undefined)) {
				entries.push(`\t\t"${id}": ${renderCost(sheet)},`);
			}
		}
	}
	return entries;
}

/** Builds the generated module's source from the models.dev dump. */
function buildCostsModule(api: unknown): string {
	const data = ModelsDevApiSchema.parse(api);
	const lines = [
		"// Copyright 2026 Shinsuke Mori",
		"// SPDX-License-Identifier: Apache-2.0",
		"//",
		"// @generated by scripts/generate-costs.ts — do not edit by hand.",
		"// Price sheets snapshotted from https://models.dev/api.json (USD per 1M",
		"// tokens): every bundled vendor's text-outputting models with a price",
		"// list. Refresh:",
		"//",
		"//   pnpm generate-costs && pnpm format",
		"",
		'import type { ModelCost } from "./schema.ts";',
		'import type { Vendor } from "./vendor-ids.ts";',
		"",
		"/** Price sheets per vendor, keyed by the vendor's model id. */",
		"export type VendorCosts = Partial<Record<Vendor, Record<string, ModelCost>>>;",
		"",
		"/** The snapshotted models.dev price sheets. */",
		"export const modelCosts: VendorCosts = {",
	];
	for (const vendor of vendors) {
		if (!(vendor in data)) {
			throw new Error(`models.dev has no "${vendor}" provider.`);
		}
		const entries = renderVendor(data[vendor]);
		if (entries.length > 0) {
			lines.push(`\t"${vendor}": {`, ...entries, "\t},");
		}
	}
	lines.push("};", "");
	return lines.join("\n");
}

if (process.argv[1] === import.meta.filename) {
	const response = await fetch(API_URL);
	if (!response.ok) {
		throw new Error(`GET ${API_URL} failed: ${response.status} ${response.statusText}`);
	}
	const out = join(import.meta.dirname, "..", "src", "costs.gen.ts");
	await writeFile(out, buildCostsModule(await response.json()));
	console.log(`wrote ${out}`);
}

export default buildCostsModule;
